/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_18_pedro_pato;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author p.rosa
 */
public class Pedro_projeto_18_pato extends javax.swing.JFrame {

    /**
     * Creates new form Pedro_projeto_18_pato
     */
    public Pedro_projeto_18_pato() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ID_pato = new javax.swing.JLabel();
        Text_ID = new javax.swing.JTextField();
        Nome_pato = new javax.swing.JLabel();
        Text_nome = new javax.swing.JTextField();
        Cadastro_pato = new javax.swing.JButton();
        Delet_pato = new javax.swing.JButton();
        Pesquisa_pato = new javax.swing.JButton();
        Att_pato = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Resultado_pes = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ID_pato.setText("ID");

        Text_ID.setText("jTextField1");
        Text_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_IDActionPerformed(evt);
            }
        });

        Nome_pato.setText("Nome");

        Text_nome.setText("jTextField2");

        Cadastro_pato.setText("Cadastro");
        Cadastro_pato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastro_patoActionPerformed(evt);
            }
        });

        Delet_pato.setText("Delete");
        Delet_pato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delet_patoActionPerformed(evt);
            }
        });

        Pesquisa_pato.setText("Pesquisa");
        Pesquisa_pato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pesquisa_patoActionPerformed(evt);
            }
        });

        Att_pato.setText("Atualizar");
        Att_pato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Att_patoActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Resultado_pes.setText("jTextField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Cadastro_pato)
                        .addGap(43, 43, 43)
                        .addComponent(Delet_pato)
                        .addGap(48, 48, 48)
                        .addComponent(Pesquisa_pato)
                        .addGap(34, 34, 34)
                        .addComponent(Att_pato))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ID_pato)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Text_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Nome_pato)
                                .addGap(37, 37, 37)
                                .addComponent(Text_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(Resultado_pes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ID_pato)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(Text_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nome_pato)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Text_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Resultado_pes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cadastro_pato)
                    .addComponent(Delet_pato)
                    .addComponent(Pesquisa_pato)
                    .addComponent(Att_pato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 841, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 38, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 38, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Text_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_IDActionPerformed

    public void popularJtabel(String sql) {


        try {
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/pato","root","");
            PreparedStatement banco = (PreparedStatement)con.prepareStatement(sql);
            banco.execute();
            
            ResultSet resultado = banco.executeQuery(sql);
            
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setNumRows (0);
            
            while (resultado.next()){
                
                model.addRow(new Object[]
                {
                    resultado.getString ("id_pato"),
                    resultado.getString ("nome_pato"),
                    
                }
                );
            }
            banco.close();
            con.close();
        } catch (SQLException ex) {
            System.out.println("Deu erro");
            System.out.println(ex.getMessage());     
        }


}
    
    private void Cadastro_patoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastro_patoActionPerformed
        try {
            Connection conexao = null;
            PreparedStatement statement = null;

            String url = "jdbc:mysql://localhost:3306/Pato";
            String usuario = "root";
            String senha = "";

            conexao = DriverManager.getConnection (url, usuario, senha) ;
            String sql = "INSERT INTO patoT (id_pato,nome_pato ) VALUES (?, ?)";

            statement = conexao.prepareStatement(sql);
            statement.setString(1, Text_ID.getText());
            statement.setString(2, Text_nome.getText());
            statement.executeUpdate();

            System.out.println("Deu certo");

            // TODO add your handling code here:
        } catch (SQLException ex) {
            System.out.println("Deu erro");
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_Cadastro_patoActionPerformed

    private void Delet_patoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delet_patoActionPerformed
        try {
            Connection conexao = null;
            PreparedStatement statement = null;

            String url = "jdbc:mysql://localhost:3306/Pato";
            String usuario = "root";
            String senha = "";

            conexao = DriverManager.getConnection (url, usuario, senha) ;
            String sql = "DELETE from patoT where id_pato = ?";

            statement = conexao.prepareStatement(sql);
            statement.setString(1, Text_ID.getText());

            statement.executeUpdate();

            System.out.println("Deu certo");

            // TODO add your handling code here:
        } catch (SQLException ex) {
            System.out.println("Deu erro");
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_Delet_patoActionPerformed

    private void Pesquisa_patoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pesquisa_patoActionPerformed
        try {
            Connection conexao = null;
            PreparedStatement statement = null;

            String url = "jdbc:mysql://localhost:3306/Pato";
            String usuario = "root";
            String senha = "";

            conexao = DriverManager.getConnection (url, usuario, senha) ;
            String sql = "SELECT nome_pato from patoT where id_pato = ?";

            statement = conexao.prepareStatement(sql);
            statement.setString(1, Text_ID.getText());
            statement.executeUpdate();
            
           ResultSet resultSet = statement.executeQuery();
           
           if(resultSet.next()){
               String nome_pato =resultSet.getString("nome");
                String nome = null;
               Resultado_pes.setText(nome_pato);
           }
           else{
              Resultado_pes.setText("Pato nao encontrado");
           }

            System.out.println("Deu certo");

            // TODO add your handling code here:
        } catch (SQLException ex) {
            System.out.println("Deu erro");
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_Pesquisa_patoActionPerformed

    private void Att_patoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Att_patoActionPerformed
        try {
            Connection conexao = null;
            PreparedStatement statement = null;

            String url = "jdbc:mysql://localhost:3306/Pato";
            String usuario = "root";
            String senha = "";

            conexao = DriverManager.getConnection (url, usuario, senha) ;
            String sql = "UPDATE patoT SET nome_pato = ? where id_pato = ?";

            statement = conexao.prepareStatement(sql);
            statement.setString(1, Text_ID.getText());
            statement.setString(2, Text_nome.getText());
            statement.executeUpdate();

            System.out.println("Deu certo");

            // TODO add your handling code here:
        } catch (SQLException ex) {
            System.out.println("Deu erro");
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_Att_patoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedro_projeto_18_pato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedro_projeto_18_pato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedro_projeto_18_pato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedro_projeto_18_pato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedro_projeto_18_pato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Att_pato;
    private javax.swing.JButton Cadastro_pato;
    private javax.swing.JButton Delet_pato;
    private javax.swing.JLabel ID_pato;
    private javax.swing.JLabel Nome_pato;
    private javax.swing.JButton Pesquisa_pato;
    private javax.swing.JTextField Resultado_pes;
    private javax.swing.JTextField Text_ID;
    private javax.swing.JTextField Text_nome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
