/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.projeto_18_pedro_pato;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author p.rosa
 */
public class Tela_pato extends javax.swing.JPanel {

    /**
     * Creates new form Tela_pato
     */
    public Tela_pato() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ID_pato = new javax.swing.JLabel();
        Text_ID = new javax.swing.JTextField();
        Nome_pato = new javax.swing.JLabel();
        Text_nome = new javax.swing.JTextField();
        Cadastro_pato = new javax.swing.JButton();
        Delet_pato = new javax.swing.JButton();
        Pesquisa_pato = new javax.swing.JButton();
        Att_pato = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ID_pato.setText("ID");

        Text_ID.setText("jTextField1");
        Text_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_IDActionPerformed(evt);
            }
        });

        Nome_pato.setText("Nome");

        Text_nome.setText("jTextField2");

        Cadastro_pato.setText("Cadastro");
        Cadastro_pato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastro_patoActionPerformed(evt);
            }
        });

        Delet_pato.setText("Delete");
        Delet_pato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delet_patoActionPerformed(evt);
            }
        });

        Pesquisa_pato.setText("Pesquisa");
        Pesquisa_pato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pesquisa_patoActionPerformed(evt);
            }
        });

        Att_pato.setText("Atualizar");
        Att_pato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Att_patoActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Cadastro_pato)
                        .addGap(43, 43, 43)
                        .addComponent(Delet_pato)
                        .addGap(48, 48, 48)
                        .addComponent(Pesquisa_pato)
                        .addGap(34, 34, 34)
                        .addComponent(Att_pato))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(ID_pato)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Text_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Nome_pato)
                            .addGap(37, 37, 37)
                            .addComponent(Text_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ID_pato)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(Text_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nome_pato)
                    .addComponent(Text_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cadastro_pato)
                    .addComponent(Delet_pato)
                    .addComponent(Pesquisa_pato)
                    .addComponent(Att_pato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 580, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void Cadastro_patoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastro_patoActionPerformed
        try {
            Connection conexao = null;
            PreparedStatement statement = null;
            
            String url = "jdbc:mysql://localhost:3306/Pato";
            String usuario = "root";
            String senha = "";
            
            conexao = DriverManager.getConnection (url, usuario, senha) ;
            String sql = "INSERT INTO pato(id_pato,nome_pato ) VALUES (?, ?)";
            
            statement = conexao.prepareStatement(sql);
            statement.setString(1, Text_ID.getText());
            statement.setString(2, Text_nome.getText());
            statement.executeUpdate();
            
            System.out.println("Deu certo");
            
            
            // TODO add your handling code here:
        } catch (SQLException ex) {
            System.out.println("Deu erro");
          System.out.println(ex.getMessage());        
        }
    }//GEN-LAST:event_Cadastro_patoActionPerformed

    private void Delet_patoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delet_patoActionPerformed
        try {
            Connection conexao = null;
            PreparedStatement statement = null;
            
            String url = "jdbc:mysql://localhost:3306/Pato";
            String usuario = "root";
            String senha = "";
            
            conexao = DriverManager.getConnection (url, usuario, senha) ;
            String sql = "DELETE from pato where id_pato = ?";
            
            statement = conexao.prepareStatement(sql);
            statement.setString(1, Text_ID.getText());

            statement.executeUpdate();
            
            System.out.println("Deu certo");
            
            
            
            // TODO add your handling code here:
        } catch (SQLException ex) {
            System.out.println("Deu erro");
          System.out.println(ex.getMessage());    
        }
    }//GEN-LAST:event_Delet_patoActionPerformed

    private void Pesquisa_patoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pesquisa_patoActionPerformed
        try {
            Connection conexao = null;
            PreparedStatement statement = null;
            
            String url = "jdbc:mysql://localhost:3306/Pato";
            String usuario = "root";
            String senha = "";
            
            conexao = DriverManager.getConnection (url, usuario, senha) ;
            String sql = "SELECT  nome_pato from pato where id_pato = ?";
            
            statement = conexao.prepareStatement(sql);
            statement.setString(1, Text_ID.getText());
            statement.setString(2, Text_nome.getText());
            statement.executeUpdate();
            
            System.out.println("Deu certo");
            
            // TODO add your handling code here:
        } catch (SQLException ex) {
            System.out.println("Deu erro");
          System.out.println(ex.getMessage());    
        }
    }//GEN-LAST:event_Pesquisa_patoActionPerformed

    private void Att_patoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Att_patoActionPerformed
        try {
            Connection conexao = null;
            PreparedStatement statement = null;
            
            String url = "jdbc:mysql://localhost:3306/Pato";
            String usuario = "root";
            String senha = "";
            
            conexao = DriverManager.getConnection (url, usuario, senha) ;
            String sql = "UPDATE pato SET nome_pato = ? where id_pato = ?";
            
            statement = conexao.prepareStatement(sql);
            statement.setString(1, Text_ID.getText());
            statement.setString(2, Text_nome.getText());
            statement.executeUpdate();
            
            System.out.println("Deu certo");
            
            
            
            
            
            // TODO add your handling code here:
        } catch (SQLException ex) {
            System.out.println("Deu erro");
          System.out.println(ex.getMessage());    
        }
    }//GEN-LAST:event_Att_patoActionPerformed

    private void Text_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_IDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Att_pato;
    private javax.swing.JButton Cadastro_pato;
    private javax.swing.JButton Delet_pato;
    private javax.swing.JLabel ID_pato;
    private javax.swing.JLabel Nome_pato;
    private javax.swing.JButton Pesquisa_pato;
    private javax.swing.JTextField Text_ID;
    private javax.swing.JTextField Text_nome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
