/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_17_pedro;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author p.rosa
 */
public class Projeto_17 extends javax.swing.JFrame {

    /**
     * Creates new form Projeto_17
     */
    public Projeto_17() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ID_L = new javax.swing.JLabel();
        Cadastrar = new javax.swing.JButton();
        Deletar = new javax.swing.JButton();
        Atualizar = new javax.swing.JButton();
        NOME_L = new javax.swing.JLabel();
        CPF_L = new javax.swing.JLabel();
        PESQUISA_L = new javax.swing.JLabel();
        Pesquisar = new javax.swing.JButton();
        Text_ID = new javax.swing.JTextField();
        Text_nome = new javax.swing.JTextField();
        Text_cpf = new javax.swing.JTextField();
        Text_pesquisa = new javax.swing.JTextField();
        Resut = new javax.swing.JLabel();
        Resulado_R = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ID_L.setText("ID");

        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });

        Deletar.setText("Deletar");
        Deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletarActionPerformed(evt);
            }
        });

        Atualizar.setText("Atualizar");
        Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarActionPerformed(evt);
            }
        });

        NOME_L.setText("Nome");

        CPF_L.setText("CPF");

        PESQUISA_L.setText("Pesquisa_ID");

        Pesquisar.setText("Pesquisar");
        Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarActionPerformed(evt);
            }
        });

        Text_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_IDActionPerformed(evt);
            }
        });

        Text_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_pesquisaActionPerformed(evt);
            }
        });

        Resut.setText("Resultado");

        Resulado_R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resulado_RActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ID_L)
                            .addComponent(NOME_L)
                            .addComponent(CPF_L)
                            .addComponent(PESQUISA_L)
                            .addComponent(Resut))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Text_ID)
                            .addComponent(Text_nome)
                            .addComponent(Text_cpf)
                            .addComponent(Text_pesquisa)
                            .addComponent(Resulado_R, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(Cadastrar)
                        .addGap(67, 67, 67)
                        .addComponent(Atualizar)
                        .addGap(66, 66, 66)
                        .addComponent(Deletar)
                        .addGap(69, 69, 69)
                        .addComponent(Pesquisar)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID_L)
                    .addComponent(Text_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NOME_L)
                    .addComponent(Text_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPF_L)
                    .addComponent(Text_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PESQUISA_L)
                    .addComponent(Text_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Resut)
                    .addComponent(Resulado_R, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cadastrar)
                    .addComponent(Atualizar)
                    .addComponent(Deletar)
                    .addComponent(Pesquisar))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        try {
            Connection conexao = null;
            PreparedStatement statement = null;
            
            String url = "jdbc:mysql://localhost:3306/Projeto_17";
            String usuario = "root";
            String senha = "";
            
            conexao = DriverManager.getConnection (url, usuario, senha) ;
            String sql = "INSERT INTO Aluno(id_aluno,nome_a,CPF) VALUES (?, ?, ?)";
            
            statement = conexao.prepareStatement(sql);
            statement.setString(1, Text_ID.getText());
            statement.setString(2, Text_nome.getText());
            statement.setString(3, Text_cpf.getText());
            statement.executeUpdate();
            
            System.out.println("Deu certo");
            
            
            
            
            // TODO add your handling code here:
        } catch (SQLException ex) {
           System.out.println("Deu erro");
          System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_CadastrarActionPerformed

    private void Text_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_IDActionPerformed

    private void Text_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_pesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_pesquisaActionPerformed

    private void AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarActionPerformed
        try {
            Connection conexao = null;
            PreparedStatement statement = null;
            
            String url = "jdbc:mysql://localhost:3306/Projeto_17";
            String usuario = "root";
            String senha = "";
            
            conexao = DriverManager.getConnection (url, usuario, senha) ;
            String sql = "UPDATE Aluno SET nome_a = ?,CPF = ?  where id_aluno = ?";
            
            statement = conexao.prepareStatement(sql);
            statement.setString(1, Text_nome.getText());
            statement.setString(2, Text_cpf.getText());
            statement.setString(3, Text_ID.getText());
            statement.executeUpdate();
            
            System.out.println("Deu certo");
            
            
            
            
            // TODO add your handling code here:
        } catch (SQLException ex) {
          System.out.println("Deu erro");
          System.out.println(ex.getMessage());        }
    }//GEN-LAST:event_AtualizarActionPerformed

    private void DeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletarActionPerformed

        try {
            Connection conexao = null;
            PreparedStatement statement = null;
            
            String url = "jdbc:mysql://localhost:3306/Projeto_17";
            String usuario = "root";
            String senha = "";
            
            conexao = DriverManager.getConnection (url, usuario, senha) ;
            String sql = "DELETE from Aluno where id_aluno = ?";
            
            statement = conexao.prepareStatement(sql);
            statement.setString(1, Text_ID.getText());

            statement.executeUpdate();
            
            System.out.println("Deu certo");
            
            
            // TODO add your handling code here:
        } catch (SQLException ex) {
          System.out.println("Deu erro");
          System.out.println(ex.getMessage()); 
        }
    }//GEN-LAST:event_DeletarActionPerformed

    private void PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarActionPerformed

        try {
            Connection conexao = null;
            PreparedStatement statement = null;
            
            String url = "jdbc:mysql://localhost:3306/Projeto_17";
            String usuario = "root";
            String senha = "";
            
            conexao = DriverManager.getConnection (url, usuario, senha) ;
            String sql = "SELECT nome_a from Aluno where id_aluno = ?";
            
            statement = conexao.prepareStatement(sql);
            statement.setString(1, Text_pesquisa.getText());

            ResultSet resultSet =  statement.executeQuery();
            if (resultSet.next()){
                try {
                    String nome_a = resultSet.getString("nome_a");
                    Resulado_R.setText(nome_a);
                } catch (SQLException ex) {
                    Logger.getLogger(N_conect_ou_Conect.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else{
                Resulado_R.setText("Aluno não encontrado");
            }
            
            
            
            
            // TODO add your handling code here:
        } catch (SQLException ex) {
          System.out.println("Deu erro");
          System.out.println(ex.getMessage());         }
    }//GEN-LAST:event_PesquisarActionPerformed

    private void Resulado_RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resulado_RActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Resulado_RActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Projeto_17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Projeto_17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Projeto_17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Projeto_17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Projeto_17().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atualizar;
    private javax.swing.JLabel CPF_L;
    private javax.swing.JButton Cadastrar;
    private javax.swing.JButton Deletar;
    private javax.swing.JLabel ID_L;
    private javax.swing.JLabel NOME_L;
    private javax.swing.JLabel PESQUISA_L;
    private javax.swing.JButton Pesquisar;
    private javax.swing.JTextField Resulado_R;
    private javax.swing.JLabel Resut;
    private javax.swing.JTextField Text_ID;
    private javax.swing.JTextField Text_cpf;
    private javax.swing.JTextField Text_nome;
    private javax.swing.JTextField Text_pesquisa;
    // End of variables declaration//GEN-END:variables
}
